# Generated by Django 5.2.8 on 2026-04-12 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_visitormessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitormessage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='visitormessage',
            name='name',
        ),
        migrations.AddField(
            model_name='visitormessage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='visitor_messages', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
