# Generated by Django 5.2.8 on 2026-06-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservote',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='Onaylandı mı?'),
        ),
    ]
